export const commands = [

    // Anime
    { "name": "peek", "desc": "Espiar a alguien.", "alias": ["/peek"], "category": "anime", "uso": "_<mention>_" },
    { "name": "comfort", "desc": "Consolar a alguien.", "alias": ["/comfort"], "category": "anime", "uso": "_<mention>_" },
    { "name": "thinkhard", "desc": "Pensar intensamente.", "alias": ["/thinkhard"], "category": "anime", "uso": "_<mention>_" },
    { "name": "curious", "desc": "Sentir curiosidad.", "alias": ["/curious"], "category": "anime", "uso": "_<mention>_" },
    { "name": "sniff", "desc": "Olfatear a alguien.", "alias": ["/sniff"], "category": "anime", "uso": "_<mention>_" },
    { "name": "stare", "desc": "Mirar fijamente.", "alias": ["/stare"], "category": "anime", "uso": "_<mention>_" },
    { "name": "trip", "desc": "Tropezar accidentalmente.", "alias": ["/trip"], "category": "anime", "uso": "_<mention>_" },
    { "name": "blowkiss", "desc": "Lanzar un beso.", "alias": ["/blowkiss"], "category": "anime", "uso": "_<mention>_" },
    { "name": "snuggle", "desc": "Acurrucarse con alguien.", "alias": ["/snuggle"], "category": "anime", "uso": "_<mention>_" },
    {"name": "angry", "desc": "Estar enojado.", "alias": ["/angry"], "category": "anime", "uso": "_<mention>_"},
    {"name": "bleh", "desc": "Sacar la lengua.", "alias": ["/bleh"], "category": "anime", "uso": "_<mention>_"},
    {"name": "bored", "desc": "Estar aburrido.", "alias": ["/bored", "/aburrido"], "category": "anime", "uso": "_<mention>_"},
    {"name": "clap", "desc": "Aplaudir.", "alias": ["/clap"], "category": "anime", "uso": "_<mention>_"},
    {"name": "coffee", "desc": "Tomar café.", "alias": ["/coffee", "/cafe"], "category": "anime", "uso": "_<mention>_"},
    { name: "cold", desc: "Mucho frío.", alias: ["/cold"], category: "anime", uso: "_<mention>_" },
    { name: "sing", desc: "Cantarle a alguien.", alias: ["/sing"], category: "anime", uso: "_<mention>_" },
    { name: "tickle", desc: "Hacer cosquillas.", alias: ["/tickle"], category: "anime", uso: "_<mention>_" },
    { name: "scream", desc: "Gritar fuerte.", alias: ["/scream"], category: "anime", uso: "_<mention>_" },
    { name: "push", desc: "Empujar a alguien.", alias: ["/push"], category: "anime", uso: "_<mention>_" },
    { name: "nope", desc: "Expresar desacuerdo.", alias: ["/nope"], category: "anime", uso: "_<mention>_" },
    { name: "jump", desc: "Saltar de felicidad.", alias: ["/jump"], category: "anime", uso: "_<mention>_" },
    { name: "heat", desc: "Sentir calor.", alias: ["/heat"], category: "anime", uso: "_<mention>_" },
    { name: "gaming", desc: "Jugar videojuegos.", alias: ["/gaming"], category: "anime", uso: "_<mention>_" },
    { name: "draw", desc: "Hacer un dibujo.", alias: ["/draw"], category: "anime", uso: "_<mention>_" },
    { name: "call", desc: "Llamar a alguien.", alias: ["/call"], category: "anime", uso: "_<mention>_" },
    {"name": "dramatic", "desc": "Hacer un drama.", "alias": ["/dramatic", "/drama"], "category": "anime", "uso": "_<mention>_"},
    {"name": "drunk", "desc": "Estar borracho.", "alias": ["/drunk"], "category": "anime", "uso": "_<mention>_"},
    {"name": "impregnate", "desc": "Embarazar.", "alias": ["/impregnate", "/preg"], "category": "anime", "uso": "_<mention>_"},
    {"name": "kisscheek", "desc": "Besar en la mejilla.", "alias": ["/kisscheek", "/beso"], "category": "anime", "uso": "_<mention>_"},
    {"name": "laugh", "desc": "Reírse.", "alias": ["/laugh"], "category": "anime", "uso": "_<mention>_"},
    {"name": "love", "desc": "Sentir atracción.", "alias": ["/love", "/amor"], "category": "anime", "uso": "_<mention>_"},
    {"name": "pout", "desc": "Hacer pucheros.", "alias": ["/pout"], "category": "anime", "uso": "_<mention>_"},
    {"name": "punch", "desc": "Dar un puñetazo.", "alias": ["/punch"], "category": "anime", "uso": "_<mention>_"},
    {"name": "run", "desc": "Correr.", "alias": ["/run", "/correr"], "category": "anime", "uso": "_<mention>_"},
    {"name": "sad", "desc": "Sentir tristeza.", "alias": ["/sad", "/triste"], "category": "anime", "uso": "_<mention>_"},
    {"name": "scared", "desc": "Estar asustado.", "alias": ["/scared"], "category": "anime", "uso": "_<mention>_"},
    {"name": "seduce", "desc": "Seducir.", "alias": ["/seduce"], "category": "anime", "uso": "_<mention>_"},
    {"name": "shy", "desc": "Sentir timidez.", "alias": ["/shy", "/timido"], "category": "anime", "uso": "_<mention>_"},
    {"name": "sleep", "desc": "Dormir.", "alias": ["/sleep"], "category": "anime", "uso": "_<mention>_"},
    {"name": "smoke", "desc": "Fumar.", "alias": ["/smoke", "/fumar"], "category": "anime", "uso": "_<mention>_"},
    {"name": "spit", "desc": "Escupir.", "alias": ["/spit", "/escupir"], "category": "anime", "uso": "_<mention>_"},
    {"name": "step", "desc": "Pisar.", "alias": ["/step", "/pisar"], "category": "anime", "uso": "_<mention>_"},
    {"name": "think", "desc": "Pensar.", "alias": ["/think"], "category": "anime", "uso": "_<mention>_"},
    {"name": "walk", "desc": "Caminar.", "alias": ["/walk"], "category": "anime", "uso": "_<mention>_"},
    {"name": "hug", "desc": "Dar un abrazo.", "alias": ["/hug"], "category": "anime", "uso": "_<mention>_"},
    {"name": "kill", "desc": "Asesinar.", "alias": ["/kill"], "category": "anime", "uso": "_<mention>_"},
    {"name": "eat", "desc": "Comer.", "alias": ["/eat", "/nom", "/comer"], "category": "anime", "uso": "_<mention>_"},
    {"name": "kiss", "desc": "Dar un beso.", "alias": ["/kiss", "/muak"], "category": "anime", "uso": "_<mention>_"},
    {"name": "wink", "desc": "Guiñar.", "alias": ["/wink"], "category": "anime", "uso": "_<mention>_"},
    {"name": "pat", "desc": "Dar una caricia.", "alias": ["/pat"], "category": "anime", "uso": "_<mention>_"},
    {"name": "happy", "desc": "Saltos de felicidad.", "alias": ["/happy", "/feliz"], "category": "anime", "uso": "_<mention>_"},
    {"name": "bully", "desc": "Hacer bullying.", "alias": ["/bully"], "category": "anime", "uso": "_<mention>_"}, 
    {"name": "bite", "desc": "Morder.", "alias": ["/bite", "/morder"], "category": "anime", "uso": "_<mention>_"},
    {"name": "blush", "desc": "Sonrojarse.", "alias": ["/blush"], "category": "anime", "uso": "_<mention>_"},
    {"name": "wave", "desc": "Saludar.", "alias": ["/wave"], "category": "anime", "uso": "_<mention>_"},
    {"name": "bath", "desc": "Bañarse.", "alias": ["/bath"], "category": "anime", "uso": "_<mention>_"},
    {"name": "smug", "desc": "Presumir.", "alias": ["/smug"], "category": "anime", "uso": "_<mention>_"},
    {"name": "smile", "desc": "Sonreír.", "alias": ["/smile"], "category": "anime", "uso": "_<mention>_"},
    {"name": "highfive", "desc": "Chocar los cinco.", "alias": ["/highfive"], "category": "anime", "uso": "_<mention>_"},
    {"name": "handhold", "desc": "Tomar de la mano.", "alias": ["/handhold"], "category": "anime", "uso": "_<mention>_"},
    {"name": "cringe", "desc": "Sentir cringe.", "alias": ["/cringe"], "category": "anime", "uso": "_<mention>_"},
    {"name": "bonk", "desc": "Golpear.", "alias": ["/bonk"], "category": "anime", "uso": "_<mention>_"},
    {"name": "cry", "desc": "Llorar.", "alias": ["/cry"], "category": "anime", "uso": "_<mention>_"},
    {"name": "lick", "desc": "Lamer.", "alias": ["/lick"], "category": "anime", "uso": "_<mention>_"},
    {"name": "slap", "desc": "Dar una bofetada.", "alias": ["/slap"], "category": "anime", "uso": "_<mention>_"},
    {"name": "dance", "desc": "Bailar.", "alias": ["/dance"], "category": "anime", "uso": "_<mention>_"},
    {"name": "cuddle", "desc": "Acurrucarse.", "alias": ["/cuddle"], "category": "anime", "uso": "_<mention>_"},

    // Downloads
    {"name": "play", "desc": "Descarga videos de youtube.", "alias": ["/play", "play2", "/mp3", "/mp4", "/playaudio", "/playvideo"], "category": "download", "uso": "_<url|query>_"},
    {"name": "facebook", "desc": "Descarga videos de facebook.", "alias": ["/facebook", "/fb"], "category": "download", "uso": "_<url>_"},
    {"name": "mediafire", "desc": "Descarga archivos de mediafire.", "alias": ["/mediafire", "/mf"], "category": "download", "uso": "_<url|query>_"},
    {"name": "tiktok", "desc": "Descarga videos de tiktok.", "alias": ["/tiktok", "/tt"], "category": "download", "uso": "_<url|query>_"},

    // Grupo
    {"name": "bot", "desc": "Activa y desactiva el bot en el grupo.", "alias": ["/bot"], "category": "grupo", "uso": "_<on|off>_"},
    {"name": "promote", "desc": "Promueve a un usuario a administrador.", "alias": ["/promote"], "category": "grupo", "uso": "_<mention>_"},
    {"name": "setprimary", "desc": "Establece un bot como primario del grupo.", "alias": ["/setprimary"], "category": "grupo", "uso": "_<mention>_"},
    {"name": "demote", "desc": "Degrada a un usuario de administrador.", "alias": ["/demote"], "category": "grupo", "uso": "_<mention>_"},
    {"name": "closet", "desc": "Cierra y abre el grupo.", "alias": ["/closet", "/open"], "category": "grupo"},
    {"name": "groupinfo", "desc": "Muestra la información del grupo.", "alias": ["/groupinfo", "/gp"], "category": "grupo"},
    {"name": "on", "desc": "Desactiva o activa las configuraciones del grupo.", "alias": ["/on", "/off"], "category": "grupo", "uso": "_<welcome|alerts|alertas|antilinks|antienlaces|onlyadmin|adminonly|nsfw>_"},
    {"name": "tag", "desc": "Menciona a todos los usuarios del grupo.", "alias": ["/tag", "/hidetag"], "category": "grupo", "uso": "_<text>_"},
    {"name": "kick", "desc": "Expulsa a un usuario del grupo.", "alias": ["/kick"], "category": "grupo", "uso": "_<mention>_"},

    // Info
    {"name": "menu", "desc": "Muestra la lista de comandos.", "alias": ["/menu", "/help"], "category": "info", "uso": "_<category>_"},
    {"name": "ping", "desc": "Muestra la velocidad del Bot.", "alias": ["/ping", "/p"], "category": "info"},
    
    // Sockets
    {"name": "bots", "desc": "Muestra el número de sockets conectados.", "alias": ["/bots", "/sockets"], "category": "sockets"},
    {"name": "logout", "desc": "Cierra la sesión del socket.", "alias": ["/logout"], "category": "sockets"},
    {"name": "qr", "desc": "Vincular un nuevo socket a tu número.", "alias": ["/qr", "/code"], "category": "sockets"},
    {"name": "leave", "desc": "El bot abandona el grupo actual.", "alias": ["/leave"], "category": "sockets"},

    // IA
    {"name": "ia", "desc": "Realiza una petición a chatgpt.", "alias": ["/ia", "/chatgpt"], "category": "ia", "uso": "_<query>_"},

    // NSFW
    {"name": "danbooru", "desc": "Buscar imágenes en danbooru.", "alias": ["/danbooru", "/dbooru"], "category": "nsfw", "uso": "_<tag>_"},
    {"name": "gelbooru", "desc": "Buscar imágenes en gelbooru.", "alias": ["/gelbooru", "/gbooru"], "category": "nsfw", "uso": "_<tag>_"},
    {"name": "blowjob", "desc": "Dale una mamada a un usuario.", "alias": ["/blowjob", "/bj"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "boobjob", "desc": "Hacerle una rusa a un usuario.", "alias": ["/boobjob"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "cum", "desc": "Venirse en alguien.", "alias": ["/cum"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "fap", "desc": "Haserse una paja.", "alias": ["/fap", "/paja"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "anal", "desc": "Hacer un anal.", "alias": ["/anal"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "grabboobs", "desc": "Agarrar las tetas de un usuario.", "alias": ["/grabboobs"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "footjob", "desc": "Hacer una paja con los pies a un usuario.", "alias": ["/footjob"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "grope", "desc": "Manosear las nalgas a un usuario.", "alias": ["/grope"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "undress", "desc": "Encuerate o encuera a un usuario.", "alias": ["/undress", "/encuerar"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "sixnine", "desc": "Hacer un 69 con un usuario.", "alias": ["/sixnine", "/69"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "lickpussy", "desc": "Lamer un coño de un usuario.", "alias": ["/lickpussy"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "spank", "desc": "Darle una nalgada a un usuario.", "alias": ["/spank", "/nalgada"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "fuck", "desc": "Coger a un usuario.", "alias": ["/fuck", "/coger"], "category": "nsfw", "uso": "_<mention>_"},
    {"name": "suckboobs", "desc": "Chupar las tetas de un usuario.", "alias": ["/suckboobs"], "category": "nsfw", "uso": "_<mention>_"},

    // Utils
    {"name": "sticker", "desc": "Convierte imágenes o videos a stickers.", "alias": ["/sticker", "/s"], "category": "utils"},
    {"name": "getpic", "desc": "Ver la foto de perfil de un usuario.", "alias": ["/getpic", "/pfp"], "category": "utils", "uso": "_<mention>_"},
    {"name": "get", "desc": "Realiza solicitudes get a páginas web.", "alias": ["/get"], "category": "utils", "uso": "_<url>_"},
    {"name": "hd", "desc": "Mejora la calidad de una imagen.", "alias": ["/hd"], "category": "utils"},
    {"name": "self", "desc": "Haz privado o público tu socket.", "alias": ["/self"], "category": "sockets", "uso": "_<on|off>_"}

];